version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
#dockerfile这里只是一个file的名字，所以还需要下面context配置来说明文件的具体位置
      dockerfile: Dockerfile.dev 
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      #just the service name
      - REDIS_HOST=redis
      #查看REDIS的doc，默认是6379
      - REDIS_PORT=6379
      #查看postgres的doc
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379